name: Result Submission
description: Submit a PawMate AI Challenge benchmark result file
title: "[submission]"
labels: ["submission", "results"]
body:
  - type: textarea
    id: result_json
    attributes:
      label: Result JSON
      description: Paste your complete result JSON file here. GitHub will automatically format and syntax-highlight the JSON when the issue is created.
      placeholder: |
        {
          "schema_version": "3.0",
          "result_data": {
            "run_identity": {
              "tool_name": "tool",
              ...
            },
            ...
          }
        }
    validations:
      required: true
